### PR TITLE
Fix VDict compatibility with tree_map.

### PR DESCRIPTION
**Pull request by apghml**

### CODE REVIEW

**Review by markblee — APPROVED** [review]
Thanks!

**Review by ruomingp — COMMENTED** [review]
Thanks! Could you check whether this will affect checkpoint backwards compatibility?

**Comment by apghml** [comment]
> Thanks! Could you check whether this will affect checkpoint backwards compatibility

Backwards compatibility unit test added.

**Comment by apghml** [comment]
Test asserts have been fixed.

**Comment by ruomingp** [comment]
> > Thanks! Could you check whether this will affect checkpoint backwards compatibility
> 
> Backwards compatibility unit test added.
> 
> The reason it doesn't affect backwards compatibility is the AXLearn checkpoint saving/restoring code doesn't track the order of dictionary keys.

Ah OK. Thanks for checking!

**Review by ruomingp — APPROVED** [review]

**Review by chongw — APPROVED** [review]

**Pull request merged**
