### PR TITLE
Support more types of groupnorm

### PR DESCRIPTION
**Pull request by berlino**
Previously, `groupnorm` assumes that layernorm is applied on all the input axes apart from batch and group axes. With this PR, we can choose to apply either RMSNorm or LayerNorm along configurable axes of input tensors.

### CODE REVIEW

**Review by ruomingp — APPROVED** [review]

**Comment by berlino** [comment]
@ruomingp  do you know why the checks are still not finished yet?

**Comment by ruomingp** [comment]
> @ruomingp do you know why the checks are still not finished yet?

I'm not sure. Maybe @markblee knows?

**Review by markblee — COMMENTED** [review]
Can you branch from a fork instead of creating a new branch in the main repo?

**Comment by ds-hwang** [comment]
@berlino Hi, since this PR is landed, ajax didn't bump axlearn. When I tried to bump, lots of golden tests are affected. Could you bump this in ajax?

**Pull request closed without merging**
