### PR TITLE
Adds Module.vprint, which uses jax.debug.print to print tensor contents

### PR DESCRIPTION
**Pull request by ruomingp**
… when verbosity is <= `Module.config.vlog`.

E.g.,
```
self.vprint(1, "output={x}", x=x)
```

prints something like

```
0826 21:52:23 module_test.py:199] @root output=31.0
```

Alternative considered: adding a flag to disable tracing, but `jax.debug.print` seems easier to use.

### CODE REVIEW

**Review by markblee — APPROVED** [review]

**Comment by ruomingp** [comment]
I ran into the following CI error---how can I reproduce locally? Thanks.

```
/root/axlearn/common/module.py:496: in vprint
    caller_frame = inspect.stack()[1]  # Get the frame of the caller (index 1).
/usr/local/lib/python3.8/inspect.py:1526: in stack
    return getouterframes(sys._getframe(1), context)
/usr/local/lib/python3.8/inspect.py:1503: in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
/usr/local/lib/python3.8/inspect.py:1473: in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
/usr/local/lib/python3.8/inspect.py:708: in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
/usr/local/lib/python3.8/inspect.py:737: in getmodule
    file = getabsfile(object, _filename)
/usr/local/lib/python3.8/inspect.py:721: in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

path = '<string>'

    def abspath(path):
        """Return an absolute path."""
        path = os.fspath(path)
        if not isabs(path):
            if isinstance(path, bytes):
                cwd = os.getcwdb()
            else:
>               cwd = os.getcwd()
E               FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by markblee** [comment]
> I ran into the following CI error---how can I reproduce locally? Thanks.
> 
> ```
> /root/axlearn/common/module.py:496: in vprint
>     caller_frame = inspect.stack()[1]  # Get the frame of the caller (index 1).
> /usr/local/lib/python3.8/inspect.py:1526: in stack
>     return getouterframes(sys._getframe(1), context)
> /usr/local/lib/python3.8/inspect.py:1503: in getouterframes
>     frameinfo = (frame,) + getframeinfo(frame, context)
> /usr/local/lib/python3.8/inspect.py:1473: in getframeinfo
>     filename = getsourcefile(frame) or getfile(frame)
> /usr/local/lib/python3.8/inspect.py:708: in getsourcefile
>     if getattr(getmodule(object, filename), '__loader__', None) is not None:
> /usr/local/lib/python3.8/inspect.py:737: in getmodule
>     file = getabsfile(object, _filename)
> /usr/local/lib/python3.8/inspect.py:721: in getabsfile
>     return os.path.normcase(os.path.abspath(_filename))
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> path = '<string>'
> 
>     def abspath(path):
>         """Return an absolute path."""
>         path = os.fspath(path)
>         if not isabs(path):
>             if isinstance(path, bytes):
>                 cwd = os.getcwdb()
>             else:
> >               cwd = os.getcwd()
> E               FileNotFoundError: [Errno 2] No such file or directory
> ```

Try running the test under a temporary directory (e.g. [TestWithTemporaryCWD](https://github.com/apple/axlearn/blob/f629d827380af9186464c9f31fadaf614f2927c5/axlearn/common/test_utils.py#L283))?

**Comment by ruomingp** [comment]
> > I ran into the following CI error---how can I reproduce locally? Thanks.
> > ```
> > /root/axlearn/common/module.py:496: in vprint
> >     caller_frame = inspect.stack()[1]  # Get the frame of the caller (index 1).
> > /usr/local/lib/python3.8/inspect.py:1526: in stack
> >     return getouterframes(sys._getframe(1), context)
> > /usr/local/lib/python3.8/inspect.py:1503: in getouterframes
> >     frameinfo = (frame,) + getframeinfo(frame, context)
> > /usr/local/lib/python3.8/inspect.py:1473: in getframeinfo
> >     filename = getsourcefile(frame) or getfile(frame)
> > /usr/local/lib/python3.8/inspect.py:708: in getsourcefile
> >     if getattr(getmodule(object, filename), '__loader__', None) is not None:
> > /usr/local/lib/python3.8/inspect.py:737: in getmodule
> >     file = getabsfile(object, _filename)
> > /usr/local/lib/python3.8/inspect.py:721: in getabsfile
> >     return os.path.normcase(os.path.abspath(_filename))
> > _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> > 
> > path = '<string>'
> > 
> >     def abspath(path):
> >         """Return an absolute path."""
> >         path = os.fspath(path)
> >         if not isabs(path):
> >             if isinstance(path, bytes):
> >                 cwd = os.getcwdb()
> >             else:
> > >               cwd = os.getcwd()
> > E               FileNotFoundError: [Errno 2] No such file or directory
> > ```
> 
> Try running the test under a temporary directory (e.g. [TestWithTemporaryCWD](https://github.com/apple/axlearn/blob/f629d827380af9186464c9f31fadaf614f2927c5/axlearn/common/test_utils.py#L283))?

Thanks! Let me try this.

**Comment by ruomingp** [comment]
Looks like the problem is fixed. Do we need another approval?

image

**Review by markblee — APPROVED** [review]

**Pull request merged**
