### PR TITLE
Rename jax.tree_util.tree_map to jax.tree.map

### PR DESCRIPTION
**Pull request by ds-hwang**
Because jax.tree_util.tree_map was deprecated.
https://jax.readthedocs.io/en/latest/changelog.html#jaxlib-0-4-27-may-7-2024

### CODE REVIEW

**Review by ruomingp — APPROVED** [review]

**Review by markblee — APPROVED** [review]

**Comment by ds-hwang** [comment]
Thank you for quick review!

**Comment by ds-hwang** [comment]
Thank you for review!
@ruomingp I cannot merge it because I don't have the write access. Could you merge it or give me a write access?

**Comment by ruomingp** [comment]
> Thank you for review! @ruomingp I cannot merge it because I don't have the write access. Could you merge it or give me a write access?

I looked around and didn't find you in https://github.com/orgs/apple/people. Could you ping Mike Drob about adding you?

**Comment by ds-hwang** [comment]
Thank you for merging it and pointer. I'll try to belong to apple/people.

**Comment by hanzhi713** [comment]
@ds-hwang From the doc, it says `jax.tree_map` is deprecated, not `jax.tree_util.tree_map`. It looks like this PR doesn't actually remove the deprecated calls to `jax.tree_map()`

> jax.tree_map() is deprecated; use jax.tree.map instead, or for backward compatibility with older JAX versions, use [jax.tree_util.tree_map()](https://jax.readthedocs.io/en/latest/_autosummary/jax.tree_util.tree_map.html#jax.tree_util.tree_map).

**Comment by hanzhi713** [comment]
@ds-hwang Should this be fixed?

**Pull request merged**
