### PR TITLE
Add Request ID to HTTP requests

### PR DESCRIPTION
**Pull request by jiya-zhang**
Potentially fixing recent error while creating queued resource

### CODE REVIEW

**Review by markblee — COMMENTED** [review]
As sync'ed offline, it seems like we're still hitting the 409's even with the unique ID.

**Comment by ruomingp** [comment]
Do we still need this PR?

**Comment by jiya-zhang** [comment]
@ruomingp Sorry this thread hasn't been the top priority but I can look into this now after my ooo. I believe some users are still seeing an error to create TPU on the first try and we'd like to improve the user experience, but the account team is stuck on reproducing the issue (haven't been able to repro)

**Comment by ruomingp** [comment]
> @ruomingp Sorry this thread hasn't been the top priority but I can look into this now after my ooo. I believe some users are still seeing an error to create TPU on the first try and we'd like to improve the user experience, but the account team is stuck on reproducing the issue (haven't been able to repro)

Got it. Thank you!

**Pull request closed without merging**
